### ISSUE TITLE
Is it possible to use a model for a subtable as a slot value

### ISSUE THREAD

**Issue by rlisper** [fukamachi/datafly#12]
Is it possible to use structure model in this case: 
`

> CONTENT> (defstruct a 
>            slot1
>            slot2
>            (slot3 '(1 2 3) :type cons))
> A
> CONTENT> (with-connection (db)
>            (execute (create-table :a_storage
>                         ((id :type 'string)
>                          (slot1 :type 'integer) 
>                          (slot2 :type 'integer))))
>            (execute (create-table :a_slot3_values
>                         ((id :type 'string) 
>                          (value :type 'integer))))
>            (execute (create-table :a_slot3_links
>                         ((id_a :type 'string)
>                          (id_slot3 :type 'string)))))                                             
> ; No value

`
I use additional table for store values of slot3 and table for a links. In this case should I to create instances of 'a' directly in the code? Doesn't exist a sugar to use AS to create 'a' automatically? Sorry, if this question isn't about datafly but I using its for learning how to work with databases. Thank you.

**Comment by fukamachi** [comment]
I'm not sure exactly what you want to do, however, datafly's models aren't related to DB tables, but the result rows.
You can 'map' results to models if those slot names are the same.
