### ISSUE TITLE
sqlite3 handle unbound error

### ISSUE THREAD

**Issue by mfiano** [fukamachi/datafly#14]
```
(connect-toplevel :sqlite3 :database-name #P"myapp.db")

(retrieve-one
  (select :*
    (from :user)
    (where (:= :name "nitro_idiot"))))
```

Using this code results in the following error, but using DBI directly works fine:

```
The slot SQLITE::HANDLE is unbound in the object
#<SQLITE-HANDLE {1007284013}>.
   [Condition of type UNBOUND-SLOT]
```

```
(let* ((query (dbi:prepare *conn* "SELECT * FROM users")) (result (dbi:execute query))) result)
#<DBD.SQLITE3::<DBD-SQLITE3-QUERY> {100284A883}>
```

**Comment by mfiano** [comment]
Upon closer inspection, I discovered that after issuing `disconnect-toplevel`, reconnecting with `connect-toplevel` has the HANDLE slot unbound in the #<SQLITE:SQLITE-HANDLE> object. Restarting the Lisp image fixes the issue. In other words, only one connection/disconnect per lisp image is possible.

**Comment by mfiano** [comment]
This seems to be because dbi:ping was tested against a database process, and not a file, and as such, the second clause in the COND of `connect-cached` will never be followed for sqlite.

**Comment by mfiano** [comment]
@fukamachi I assume this issue is not going to be addressed? It makes using sqlite3 with datafly very broken and I have to resort to CLSQL until this is resolved.

**Comment by gkbrk** [comment]
@fukamachi This issue affected me as well, if sqlite is supported by datafly it would be great if it could be supported for multiple toplevel connections as well.

**Comment by fukamachi** [comment]
It was an issue of SQLite3 driver, which raised an UNBOUND-SLOT error when calling `dbi:ping` for a disconnected connection.
It'd fixed at the above referenced commit.

Thank you for reporting and sorry for the delay.
