### ISSUE TITLE
Does not build with latest ITERATE and SXQL - symbol conflict

### ISSUE THREAD

**Issue by quicklisp** [fukamachi/datafly#15]
I get a symbol conflict between `sxql:for` and `iterate:for` in Datafly today.

**Comment by fukamachi** [comment]
Thanks for letting me know that!

**Comment by quicklisp** [comment]
This is also an issue in `integral` - I can make another issue for that project.

**Comment by fukamachi** [comment]
Okay, I added a commit to Integral which should fix it.
