### ISSUE TITLE
The result of encode-json is error, when the list has only one member

### ISSUE THREAD

**Issue by ly5156** [fukamachi/datafly#5]
My case is
 (datafly:encode-json  '((COMMENT-ID 4 COMMENT-AUTHOR liuyan COMMENT-TEXT testcomment)))
The error result is
"{\"commentId\":[4,\"commentAuthor\",\"liuyan\",\"commentText\",\"testcomment\"]}"
And the right result should be
"[{\"commentid\":4,\"commentauthor\":\"liuyan\",\"commenttext\":\"testcomment\"}]"

**Comment by fukamachi** [comment]
It's a known issue. Because it also looks like an association list.

**Comment by ly5156** [comment]
Thank your answer.
It's very helpful to me.
