### ISSUE TITLE
AUTOINCREMENT (sqlite) vs AUTO_INCREMENT (MySQL) vs :type serial (pgsql)

### ISSUE THREAD

**Issue by knobo** [fukamachi/datafly#6]
Is there any way to absctract away the differences in auto increment functionality in the different databases? I think autoincrement on sqlite does not work at all. Auto_increment only works for mysql.

**Comment by fukamachi** [comment]
It's out of scope. Datafly doesn't care of DB schema.

**Comment by knobo** [comment]
Ok, this is an sxql issue, then.

**Comment by fukamachi** [comment]
It isn't an issue of SxQL either.
The scope of SxQL is only providing an S-expression representation of SQL,
not abstracting the SQL implementation differences.
